version : "3.1"

services:
  front:
    container_name : front
    build: ./
    command : npm start
    restart: always
    ports: 
      - "3000:3000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - front
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - webserver
    volumes:
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email almas@gmail.com  --agree-tos --no-eff-email -d admin.loom.kz
  volumes:
    www-html:
    etc-letsencrypt:

       
